### Login
POST http://localhost:3000/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "alex92.serenko@gmail.com"
}

### Register
POST http://localhost:3000/auth/register
Content-Type: application/json
Accept: application/json


{
  "firstname": "Alex",
  "lastname": "Serenko",
  "email": "alex92.serenko@gmail.com"
}


### Confirm
POST http://localhost:3000/auth/confirm
Content-Type: application/json
Accept: application/json

{
  "email": "alex92.serenko@gmail.com",
  "code": "07986"
}
