### Login
POST http://localhost:3333/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "alex92.serenko@gmail.com"
}

### Confirm
POST http://localhost:3333/auth/confirm
Content-Type: application/json
Accept: application/json

{
  "email": "alex92.serenko@gmail.com",
  "code": "44383"
}
