export interface Card {
  readonly id: number;
  readonly code: number;
  readonly isoCode: string;
  readonly major: boolean;
}

export enum CardMajor {
  TheFool = '0',
  TheMagician = 'I',
  TheHighPriestess = 'II',
  TheEmpress = 'III',
  TheEmperor = 'IV',
  TheHierophant = 'V',
  TheLovers = 'VI',
  TheChariot = 'VII',
  Strength = 'VIII',
  TheHermit = 'IX',
  WheelOfFortune = 'X',
  Justice = 'XI',
  TheHangedMan = 'XII',
  Death = 'XIII',
  Temperance = 'XIV',
  TheDevil = 'XV',
  TheTower = 'XVI',
  TheStar = 'XVII',
  TheMoon = 'XVIII',
  TheSun = 'XIX',
  Judgement = 'XX',
  TheWorld = 'XXI',
}

export enum CardMinor {
  AceOfCups = 'CI',
  TwoOfCups = 'CII',
  ThreeOfCups = 'CIII',
  FourOfCups = 'CIV',
  FiveOfCups = 'CV',
  SixOfCups = 'CVI',
  SevenOfCups = 'CVII',
  EightOfCups = 'CVIII',
  NineOfCups = 'CIX',
  TenOfCups = 'CX',
  PageOfCups = 'CXI',
  KnightOfCups = 'CXII',
  QueenOfCups = 'CXIII',
  KingOfCups = 'CXIV',

  AceOfPentacles = 'PI',
  TwoOfPentacles = 'PII',
  ThreeOfPentacles = 'PIII',
  FourOfPentacles = 'PIV',
  FiveOfPentacles = 'PV',
  SixOfPentacles = 'PVI',
  SevenOfPentacles = 'PVII',
  EightOfPentacles = 'PVIII',
  NineOfPentacles = 'PIX',
  TenOfPentacles = 'PX',
  PageOfPentacles = 'PXI',
  KnightOfPentacles = 'PXII',
  QueenOfPentacles = 'PXIII',
  KingOfPentacles = 'PXIV',

  AceOfWands = 'WI',
  TwoOfWands = 'WII',
  ThreeOfWands = 'WIII',
  FourOfWands = 'WIV',
  FiveOfWands = 'WV',
  SixOfWands = 'WVI',
  SevenOfWands = 'WVII',
  EightOfWands = 'WVIII',
  NineOfWands = 'WIX',
  TenOfWands = 'WX',
  PageOfWands = 'WXI',
  KnightOfWands = 'WXII',
  QueenOfWands = 'WXIII',
  KingOfWands = 'WXIV',

  AceOfSwords = 'SI',
  TwoOfSwords = 'SII',
  ThreeOfSwords = 'SIII',
  FourOfSwords = 'SIV',
  FiveOfSwords = 'SV',
  SixOfSwords = 'SVI',
  SevenOfSwords = 'SVII',
  EightOfSwords = 'SVIII',
  NineOfSwords = 'SIX',
  TenOfSwords = 'SX',
  PageOfSwords = 'SXI',
  KnightOfSwords = 'SXII',
  QueenOfSwords = 'SXIII',
  KingOfSwords = 'SXIV',
}

export const MAJOR_CARDS: Card[] = [
  {
    id: 1,
    code: 1,
    isoCode: CardMajor.TheMagician,
    major: true,
  },
  {
    id: 2,
    code: 2,
    isoCode: CardMajor.TheHighPriestess,
    major: true,
  },
  {
    id: 3,
    code: 3,
    isoCode: CardMajor.TheEmpress,
    major: true,
  },
  {
    id: 4,
    code: 4,
    isoCode: CardMajor.TheEmperor,
    major: true,
  },
  {
    id: 5,
    code: 5,
    isoCode: CardMajor.TheHierophant,
    major: true,
  },
  {
    id: 6,
    code: 6,
    isoCode: CardMajor.TheLovers,
    major: true,
  },
  {
    id: 7,
    code: 7,
    isoCode: CardMajor.TheChariot,
    major: true,
  },
  {
    id: 8,
    code: 8,
    isoCode: CardMajor.Strength,
    major: true,
  },
  {
    id: 9,
    code: 9,
    isoCode: CardMajor.TheHermit,
    major: true,
  },
  {
    id: 10,
    code: 10,
    isoCode: CardMajor.WheelOfFortune,
    major: true,
  },
  {
    id: 11,
    code: 11,
    isoCode: CardMajor.Justice,
    major: true,
  },
  {
    id: 12,
    code: 12,
    isoCode: CardMajor.TheHangedMan,
    major: true,
  },
  {
    id: 13,
    code: 13,
    isoCode: CardMajor.Death,
    major: true,
  },
  {
    id: 14,
    code: 14,
    isoCode: CardMajor.Temperance,
    major: true,
  },
  {
    id: 15,
    code: 15,
    isoCode: CardMajor.TheDevil,
    major: true,
  },
  {
    id: 16,
    code: 16,
    isoCode: CardMajor.TheTower,
    major: true,
  },
  {
    id: 17,
    code: 17,
    isoCode: CardMajor.TheStar,
    major: true,
  },
  {
    id: 18,
    code: 18,
    isoCode: CardMajor.TheMoon,
    major: true,
  },
  {
    id: 19,
    code: 19,
    isoCode: CardMajor.TheSun,
    major: true,
  },
  {
    id: 20,
    code: 20,
    isoCode: CardMajor.Judgement,
    major: true,
  },
  {
    id: 21,
    code: 21,
    isoCode: CardMajor.TheWorld,
    major: true,
  },
  {
    id: 22,
    code: 22,
    isoCode: CardMajor.TheFool,
    major: true,
  },
] as const;

export const MINOR_CARDS: Card[] = [
  {
    id: 23,
    code: 101,
    isoCode: CardMinor.AceOfCups,
    major: false,
  },
  {
    id: 24,
    code: 102,
    isoCode: CardMinor.TwoOfCups,
    major: false,
  },
  {
    id: 25,
    code: 103,
    isoCode: CardMinor.ThreeOfCups,
    major: false,
  },
  {
    id: 26,
    code: 104,
    isoCode: CardMinor.FourOfCups,
    major: false,
  },
  {
    id: 27,
    code: 105,
    isoCode: CardMinor.FiveOfCups,
    major: false,
  },
  {
    id: 28,
    code: 106,
    isoCode: CardMinor.SixOfCups,
    major: false,
  },
  {
    id: 29,
    code: 107,
    isoCode: CardMinor.SevenOfCups,
    major: false,
  },
  {
    id: 30,
    code: 108,
    isoCode: CardMinor.EightOfCups,
    major: false,
  },
  {
    id: 31,
    code: 109,
    isoCode: CardMinor.NineOfCups,
    major: false,
  },
  {
    id: 32,
    code: 110,
    isoCode: CardMinor.TenOfCups,
    major: false,
  },
  {
    id: 33,
    code: 111,
    isoCode: CardMinor.PageOfCups,
    major: false,
  },
  {
    id: 34,
    code: 112,
    isoCode: CardMinor.KnightOfCups,
    major: false,
  },
  {
    id: 35,
    code: 113,
    isoCode: CardMinor.QueenOfCups,
    major: false,
  },
  {
    id: 36,
    code: 114,
    isoCode: CardMinor.KingOfCups,
    major: false,
  },
  {
    id: 37,
    code: 201,
    isoCode: CardMinor.AceOfPentacles,
    major: false,
  },
  {
    id: 38,
    code: 202,
    isoCode: CardMinor.TwoOfPentacles,
    major: false,
  },
  {
    id: 39,
    code: 203,
    isoCode: CardMinor.ThreeOfPentacles,
    major: false,
  },
  {
    id: 40,
    code: 204,
    isoCode: CardMinor.FourOfPentacles,
    major: false,
  },
  {
    id: 41,
    code: 205,
    isoCode: CardMinor.FiveOfPentacles,
    major: false,
  },
  {
    id: 42,
    code: 206,
    isoCode: CardMinor.SixOfPentacles,
    major: false,
  },
  {
    id: 43,
    code: 207,
    isoCode: CardMinor.SevenOfPentacles,
    major: false,
  },
  {
    id: 44,
    code: 208,
    isoCode: CardMinor.EightOfPentacles,
    major: false,
  },
  {
    id: 45,
    code: 209,
    isoCode: CardMinor.NineOfPentacles,
    major: false,
  },
  {
    id: 46,
    code: 210,
    isoCode: CardMinor.TenOfPentacles,
    major: false,
  },
  {
    id: 47,
    code: 211,
    isoCode: CardMinor.PageOfPentacles,
    major: false,
  },
  {
    id: 48,
    code: 212,
    isoCode: CardMinor.KnightOfPentacles,
    major: false,
  },
  {
    id: 49,
    code: 213,
    isoCode: CardMinor.QueenOfPentacles,
    major: false,
  },
  {
    id: 50,
    code: 214,
    isoCode: CardMinor.KingOfPentacles,
    major: false,
  },
  {
    id: 51,
    code: 301,
    isoCode: CardMinor.AceOfWands,
    major: false,
  },
  {
    id: 52,
    code: 302,
    isoCode: CardMinor.TwoOfWands,
    major: false,
  },
  {
    id: 53,
    code: 303,
    isoCode: CardMinor.ThreeOfWands,
    major: false,
  },
  {
    id: 54,
    code: 304,
    isoCode: CardMinor.FourOfWands,
    major: false,
  },
  {
    id: 55,
    code: 305,
    isoCode: CardMinor.FiveOfWands,
    major: false,
  },
  {
    id: 56,
    code: 306,
    isoCode: CardMinor.SixOfWands,
    major: false,
  },
  {
    id: 57,
    code: 307,
    isoCode: CardMinor.SevenOfWands,
    major: false,
  },
  {
    id: 58,
    code: 308,
    isoCode: CardMinor.EightOfWands,
    major: false,
  },
  {
    id: 59,
    code: 309,
    isoCode: CardMinor.NineOfWands,
    major: false,
  },
  {
    id: 60,
    code: 310,
    isoCode: CardMinor.TenOfWands,
    major: false,
  },
  {
    id: 61,
    code: 311,
    isoCode: CardMinor.PageOfWands,
    major: false,
  },
  {
    id: 62,
    code: 312,
    isoCode: CardMinor.KnightOfWands,
    major: false,
  },
  {
    id: 63,
    code: 313,
    isoCode: CardMinor.QueenOfWands,
    major: false,
  },
  {
    id: 64,
    code: 314,
    isoCode: CardMinor.KingOfWands,
    major: false,
  },
  {
    id: 65,
    code: 401,
    isoCode: CardMinor.AceOfSwords,
    major: false,
  },
  {
    id: 66,
    code: 402,
    isoCode: CardMinor.TwoOfSwords,
    major: false,
  },
  {
    id: 67,
    code: 403,
    isoCode: CardMinor.ThreeOfSwords,
    major: false,
  },
  {
    id: 68,
    code: 404,
    isoCode: CardMinor.FourOfSwords,
    major: false,
  },
  {
    id: 69,
    code: 405,
    isoCode: CardMinor.FiveOfSwords,
    major: false,
  },
  {
    id: 70,
    code: 406,
    isoCode: CardMinor.SixOfSwords,
    major: false,
  },
  {
    id: 71,
    code: 407,
    isoCode: CardMinor.SevenOfSwords,
    major: false,
  },
  {
    id: 72,
    code: 408,
    isoCode: CardMinor.EightOfSwords,
    major: false,
  },
  {
    id: 73,
    code: 409,
    isoCode: CardMinor.NineOfSwords,
    major: false,
  },
  {
    id: 74,
    code: 410,
    isoCode: CardMinor.TenOfSwords,
    major: false,
  },
  {
    id: 75,
    code: 411,
    isoCode: CardMinor.PageOfSwords,
    major: false,
  },
  {
    id: 76,
    code: 412,
    isoCode: CardMinor.KnightOfSwords,
    major: false,
  },
  {
    id: 77,
    code: 413,
    isoCode: CardMinor.QueenOfSwords,
    major: false,
  },
  {
    id: 78,
    code: 414,
    isoCode: CardMinor.KingOfSwords,
    major: false,
  },
] as const;

export const CARDS: Card[] = [...MAJOR_CARDS, ...MINOR_CARDS];
